# This is a basic workflow to help you get started with Actions

name: Nerd

# Controls when the workflow will run
on:
  schedule:
    - cron: '45 14 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Get current day
        id: date
        run: echo "TDAY=$(date +'%A')" >> $GITHUB_ENV
      - name: Snipe
        id: snipe
        uses: snow-actions/tweet@v1.1.2
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        with:
          status: "@marclittlemore today is ${{ env.TDAY }}!"
      - run: echo "${TWEET_ID}"
        env:
          TWEET_ID: ${{ fromJSON(steps.snipe.outputs.response).id_str }}
